version: "3.8"

services:
  mongodb:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
    networks:
      - socialbeats-network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    restart: unless-stopped
    image: redis:7-alpine
    container_name: redis-auth
    networks:
      - socialbeats-network
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  auth-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: auth-service
    environment:
      - MONGOURL=${MONGOURL}
      - MONGOADMIN=${MONGOADMIN}
      - MONGOPASS=${MONGOPASS}
      - NODE_ENV=production
      - PORT=${PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRY=${JWT_ACCESS_EXPIRY}
      - JWT_REFRESH_EXPIRY=${JWT_REFRESH_EXPIRY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - API_TITLE=${API_TITLE}
      - API_DESCRIPTION=${API_DESCRIPTION}
    depends_on:
      - mongodb
      - redis
    networks:
      - socialbeats-network
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app:cached
      - /app/node_modules
    command: nodemon --watch /app --legacy-watch --polling-interval 1000 main.js

volumes:
  mongo-data:
  redis-data:

networks:
  socialbeats-network:
    external: true